#!/usr/bin/env node
/*
 * Tabula — spreadsheet-style new tab page browser extension.
 *
 * Copyright (C) 2026 withersky
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
"use strict";

// Генератор браузерных i18n-скриптов из JSON-словарей.
//
// Исходники:  src/i18n/<lang>.json, src/i18n/symbols.<lang>.json
// Результат:  src/i18n/generated/ui.js       → глобал I18N_DATA
//             src/i18n/generated/symbols.js  → глобал I18N_SYMBOLS
//
// Скрипты рассчитаны на подключение классическим <script>/importScripts
// (не ES-модули), поэтому вешают данные на глобальный объект — window в
// страницах, self в service worker, globalThis в Node.
//
// Переводы на новых языках добавляются так:
//   1) положить src/i18n/<lang>.json (и при желании symbols.<lang>.json);
//   2) запустить `node scripts/gen-i18n.mjs` или build.sh — данные
//      попадут в generated-скрипты автоматически.
//
// Все языки (коды ISO 639-1: ru, en, es, fr, zh, ar, …) определяются
// автоматически по наличию файлов в src/i18n/, жёсткого списка нет.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const I18N_DIR = path.join(ROOT, "src", "i18n");
const OUT_DIR = path.join(I18N_DIR, "generated");

function readJson(file) {
  return JSON.parse(readFileSync(path.join(I18N_DIR, file), "utf8"));
}

// Автоматически находим все языки по файлам <lang>.json в src/i18n/.
// Жёсткого списка нет: новый язык добавляется просто файлом <lang>.json.
const LANG_RE = /^([a-z]{2,3})\.json$/;
const SYM_RE = /^symbols\.([a-z]{2,3})\.json$/;

const uiLangs = {};
const symLangs = {};
for (const f of readdirSync(I18N_DIR)) {
  let m = f.match(LANG_RE);
  if (m) {
    const lang = m[1];
    if (lang === "symbols") continue; // не путать с symbols.<lang>.json
    uiLangs[lang] = readJson(f);
    continue;
  }
  m = f.match(SYM_RE);
  if (m) symLangs[m[1]] = readJson(f);
}

// Сортируем коды языков для стабильного порядка в сгенерированном файле:
// сначала «базовые» ru/en, затем остальные по алфавиту.
const sortLangs = (obj) =>
  Object.keys(obj).sort((a, b) => {
    const rank = (x) => (x === "ru" ? 0 : x === "en" ? 1 : 2);
    const ra = rank(a), rb = rank(b);
    return ra !== rb ? ra - rb : a.localeCompare(b);
  });

function buildLangsMap(obj) {
  const out = {};
  for (const lang of sortLangs(obj)) out[lang] = obj[lang];
  return out;
}

function writeBridge(name, globalName, langs) {
  const body = Object.keys(langs)
    .map((lang) => `    ${lang}: ${JSON.stringify(langs[lang], null, 2).replace(/\n/g, "\n    ")}`)
    .join(",\n");
  const src =
    "// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.\n" +
    "// Source: src/i18n/*.json\n" +
    "//\n" +
    "// Tabula — spreadsheet-style new tab page browser extension.\n" +
    "// Copyright (C) 2026 withersky. Licensed under GPL-3.0-or-later:\n" +
    "// https://www.gnu.org/licenses/gpl-3.0.html\n" +
    "(function (g) {\n" +
    '  "use strict";\n' +
    `  g.${globalName} = {\n` +
    `${body}\n` +
    "  };\n" +
    '})(typeof globalThis !== "undefined" ? globalThis : this);\n';
  writeFileSync(path.join(OUT_DIR, name), src, "utf8");
  return src;
}

mkdirSync(OUT_DIR, { recursive: true });

const uiMap = buildLangsMap(uiLangs);
const symMap = buildLangsMap(symLangs);

writeBridge("ui.js", "I18N_DATA", uiMap);
writeBridge("symbols.js", "I18N_SYMBOLS", symMap);

console.log(
  `i18n: generated ui.js (${Object.keys(uiMap).length} langs, ` +
  `${Object.values(uiMap).reduce((n, d) => n + Object.keys(d).length, 0)} keys) ` +
  `and symbols.js (${Object.keys(symMap).length} langs, ` +
  `${Object.values(symMap).reduce((n, d) => n + Object.keys(d).length, 0)} keys)`
);
