#!/usr/bin/env node
/*
 * Tabula — spreadsheet-style new tab page browser extension.
 *
 * Copyright (C) 2026 withersky
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
"use strict";

// Генератор браузерных i18n-скриптов из JSON-словарей.
//
// Исходники:  src/i18n/{ru,en}.json, src/i18n/symbols.{ru,en}.json
// Результат:  src/i18n/generated/ui.js       → глобал I18N_DATA
//             src/i18n/generated/symbols.js  → глобал I18N_SYMBOLS
//
// Скрипты рассчитаны на подключение классическим <script>/importScripts
// (не ES-модули), поэтому вешают данные на глобальный объект — window в
// страницах, self в service worker, globalThis в Node.
//
// Переводы на новых языках добавляются так:
//   1) положить src/i18n/<lang>.json (и при желании symbols.<lang>.json);
//   2) запустить `node scripts/gen-i18n.mjs` или build.sh — данные
//      попадут в generated-скрипты автоматически.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const I18N_DIR = path.join(ROOT, "src", "i18n");
const OUT_DIR = path.join(I18N_DIR, "generated");

function readJson(file) {
  return JSON.parse(readFileSync(path.join(I18N_DIR, file), "utf8"));
}

function writeBridge(name, globalName, langs) {
  const body = Object.keys(langs)
    .map((lang) => `    ${lang}: ${JSON.stringify(langs[lang], null, 2).replace(/\n/g, "\n    ")}`)
    .join(",\n");
  const src =
    "// AUTO-GENERATED by scripts/gen-i18n.mjs — do not edit.\n" +
    "// Source: src/i18n/*.json\n" +
    "//\n" +
    "// Tabula — spreadsheet-style new tab page browser extension.\n" +
    "// Copyright (C) 2026 withersky. Licensed under GPL-3.0-or-later:\n" +
    "// https://www.gnu.org/licenses/gpl-3.0.html\n" +
    "(function (g) {\n" +
    '  "use strict";\n' +
    `  g.${globalName} = {\n` +
    `${body}\n` +
    "  };\n" +
    '})(typeof globalThis !== "undefined" ? globalThis : this);\n';
  writeFileSync(path.join(OUT_DIR, name), src, "utf8");
  return src;
}

mkdirSync(OUT_DIR, { recursive: true });

const ru = readJson("ru.json");
const en = readJson("en.json");
const symbolsRu = readJson("symbols.ru.json");
const symbolsEn = readJson("symbols.en.json");

writeBridge("ui.js", "I18N_DATA", { ru, en });
writeBridge("symbols.js", "I18N_SYMBOLS", { ru: symbolsRu, en: symbolsEn });

console.log(
  `i18n: generated ui.js (${Object.keys(ru).length + Object.keys(en).length} keys) ` +
  `and symbols.js (${Object.keys(symbolsRu).length + Object.keys(symbolsEn).length} keys)`
);
